project:
  type: website
  output-dir: docs

website:
  title: "Nicole Pepper"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resources.qmd
        text: Resources

format:
  html:
    theme:
      light: cosmo
      dark: solar
    css: styles.css
    toc: false
    page-layout: full


