project:
  type: website
  output-dir: docs

website:
  favicon: images/pepper-logo.png
  navbar:
    logo: images/np-logo.png
    right:
      - href: index.qmd
        text: Home
      - href: maps_and_data_viz.qmd
        text: Portfolio
      - href: blogs.qmd
        text: Blogs

  page-footer: 
    background: light
    left: Copyright 2021, Nicole Pepper
    right: This website was built with {{< fa brands github title='GitHub' >}}
  
format:
  html:
    theme: styles.scss
    toc: false
    page-layout: full
    mainfont: Poppins
    monofont: Poppins
    

    


