<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Nicole Pepper">
<meta name="dcterms.date" content="2024-12-04">
<meta name="description" content="Using Satellite &amp; Air Quality Data in Python">

<title>A Step-By-Step Analysis of the Impacts of the Thomas Fire</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../images/pepper-logo.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../images/np-logo.png" alt="" class="navbar-logo">
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../portfolio.html"> 
<span class="menu-text">Portfolio</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../blogs.html"> 
<span class="menu-text">Blogs</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-page-left">
      <h1 class="title">A Step-By-Step Analysis of the Impacts of the Thomas Fire</h1>
                  <div>
        <div class="description">
          Using Satellite &amp; Air Quality Data in Python
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">GIS</div>
                <div class="quarto-category">Remote-Sensing</div>
                <div class="quarto-category">MEDS</div>
                <div class="quarto-category">Python</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta column-page-left">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Nicole Pepper </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">December 4, 2024</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#part-1.-visualizing-the-thomas-fire-burn-scar-using-false-color" id="toc-part-1.-visualizing-the-thomas-fire-burn-scar-using-false-color" class="nav-link active" data-scroll-target="#part-1.-visualizing-the-thomas-fire-burn-scar-using-false-color">Part 1. Visualizing the Thomas Fire burn scar using false color</a>
  <ul class="collapse">
  <li><a href="#step-1e.-visualize-the-landsat-data-in-true-color" id="toc-step-1e.-visualize-the-landsat-data-in-true-color" class="nav-link" data-scroll-target="#step-1e.-visualize-the-landsat-data-in-true-color">Step 1E. Visualize the Landsat data in true color</a></li>
  <li><a href="#step-1f.-visualize-the-landsat-data-in-false" id="toc-step-1f.-visualize-the-landsat-data-in-false" class="nav-link" data-scroll-target="#step-1f.-visualize-the-landsat-data-in-false">Step 1F. Visualize the Landsat data in false</a></li>
  <li><a href="#step-1g.-overlay-the-thomas-fire-boundary-on-the-false-color-image" id="toc-step-1g.-overlay-the-thomas-fire-boundary-on-the-false-color-image" class="nav-link" data-scroll-target="#step-1g.-overlay-the-thomas-fire-boundary-on-the-false-color-image">Step 1G. Overlay the Thomas Fire boundary on the false color image</a></li>
  </ul></li>
  <li><a href="#part-2.-timeseries-analysis-of-the-thomas-fires-impact-on-regional-air-quality" id="toc-part-2.-timeseries-analysis-of-the-thomas-fires-impact-on-regional-air-quality" class="nav-link" data-scroll-target="#part-2.-timeseries-analysis-of-the-thomas-fires-impact-on-regional-air-quality">Part 2. Timeseries Analysis of the Thomas Fire’s Impact on Regional Air Quality</a>
  <ul class="collapse">
  <li><a href="#step-2a-set-up-my-workspace" id="toc-step-2a-set-up-my-workspace" class="nav-link" data-scroll-target="#step-2a-set-up-my-workspace">Step 2A: Set up my workspace</a></li>
  <li><a href="#step-2b-import-prepare-data" id="toc-step-2b-import-prepare-data" class="nav-link" data-scroll-target="#step-2b-import-prepare-data">Step 2B: Import &amp; prepare data</a></li>
  <li><a href="#step-2c.-explore-the-data" id="toc-step-2c.-explore-the-data" class="nav-link" data-scroll-target="#step-2c.-explore-the-data">Step 2C. Explore the Data</a></li>
  <li><a href="#step-2d.-prepare-the-aqi-data-for-visualization" id="toc-step-2d.-prepare-the-aqi-data-for-visualization" class="nav-link" data-scroll-target="#step-2d.-prepare-the-aqi-data-for-visualization">Step 2D. Prepare the AQI data for visualization</a></li>
  <li><a href="#step-2e.-subset-prepare-aqi-data-for-timeseries-visualization" id="toc-step-2e.-subset-prepare-aqi-data-for-timeseries-visualization" class="nav-link" data-scroll-target="#step-2e.-subset-prepare-aqi-data-for-timeseries-visualization">Step 2E. Subset &amp; prepare <code>aqi</code> data for timeseries visualization</a></li>
  <li><a href="#step-2f.-calculate-5-day-rolling-average-for-aqi" id="toc-step-2f.-calculate-5-day-rolling-average-for-aqi" class="nav-link" data-scroll-target="#step-2f.-calculate-5-day-rolling-average-for-aqi">Step 2F. Calculate 5-Day Rolling Average for AQI</a></li>
  <li><a href="#step-2e.-create-aqi-time-series-plot-for-the-thomas-fire" id="toc-step-2e.-create-aqi-time-series-plot-for-the-thomas-fire" class="nav-link" data-scroll-target="#step-2e.-create-aqi-time-series-plot-for-the-thomas-fire">Step 2E. Create AQI Time Series Plot for the Thomas Fire</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References:</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block column-page-left" id="quarto-document-content">





<p><img src="nasa-eo-fire.jpg" class="img-fluid"></p>
<p>Source: <a href="https://earthobservatory.nasa.gov/images/91421/fires-continue-to-rage-in-southern-california">NASA Earth Observatory</a></p>
<p>The Thomas Fire, which ignited on December 4, 2017, burned approximately 281,893 acres in Ventura and Santa Barbara counties, making it one of the largest and most devastating wildfires in California’s history. The fire left behind extensive burn scars with widespread loss of vegetation and unstable soil, leaving the region vulnerable to erosion. In 2018, heavy rains caused massive flooding and debris flows, which resulted in catastrophic damage and tragic loss of life.</p>
<p>Here I share my beginner’s <code>Python</code> exercise exploring some of the impacts of the Thomas Fire using satellite imagery and air quality data.</p>
<section id="part-1.-visualizing-the-thomas-fire-burn-scar-using-false-color" class="level2">
<h2 class="anchored" data-anchor-id="part-1.-visualizing-the-thomas-fire-burn-scar-using-false-color">Part 1. Visualizing the Thomas Fire burn scar using false color</h2>
<p>Satellite data can be used to visualize landscapes beyond what the bare eye can see. In this section I utilize true color and false color settings to visualize the Thomas Fire burn area.</p>
<p>Some of the technical highlights for this section include working with satellite imagery with <code>rioxr</code>, working with geospatial data with <code>geopandas</code>, and creating a map with <code>matplotlib</code>.</p>
<section id="step-1a-set-up-my-workspace" class="level4">
<h4 class="anchored" data-anchor-id="step-1a-set-up-my-workspace">Step 1A: Set up my workspace</h4>
<p>To begin work this exercise I set up my workspace by loading in the libraries that are necessary for the analysis:</p>
<div id="c9d637e5-87af-4633-8795-c1104c1d0a45" class="cell" data-tags="[]" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ---- Load libraries ----</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> os <span class="co"># interacting with operating system</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np <span class="co"># numeric computing</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt <span class="co"># data visualization</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd <span class="co"># general data wrangling</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> geopandas <span class="im">as</span> gpd <span class="co"># geospatial data wrangling</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> shapely.geometry <span class="im">import</span> Polygon <span class="co"># creating and manipulating geometric objects</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyproj <span class="im">import</span> CRS <span class="co"># crs management</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> rioxarray <span class="im">as</span> rioxr <span class="co"># working with raster data</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> xarray <span class="im">as</span> xr <span class="co"># working with arrays</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then I configure my working environment and establish a directory structure for managing the project data.</p>
<div id="55f5dedb-43aa-403d-bfc9-d79c47319c32" class="cell" data-tags="[]" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ---- Set working environment ----</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Set anaconda environment</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>os.environ[<span class="st">'PROJ_LIB'</span>] <span class="op">=</span> <span class="st">'/opt/anaconda3/share/proj'</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Set up a root path directory</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>root <span class="op">=</span> os.path.join(<span class="st">'/'</span>,</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>                  <span class="st">'courses'</span>,</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>                  <span class="st">'EDS220'</span>,</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>                  <span class="st">'data'</span>,</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>                  <span class="st">'hwk4_landsat_data'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="step-1b-import-prepare-data" class="level4">
<h4 class="anchored" data-anchor-id="step-1b-import-prepare-data">Step 1B: Import &amp; prepare data</h4>
<p>Next it’s time to read in my project data.</p>
<p>The <code>thomas_fire.shp</code> is a shapefile containing the fire perimeter for the Thomas Fire in 2017. It is subset of a CAL FIRE dataset with historical boundaries for fires (including both natural and prescribed fires) in the state of California. The dataset has a good record of past large fires but is not complete and may be missing some fires. I subset the Thomas Fire from the CAL FIRE dataset for this exercise, check out <a href="https://github.com/nicolelpepper/eds220-hwk4/blob/main/hwk4-task2-fire-perimeter-PEPPER.ipynb">this notebook on GitHub</a> if you’d like to see how I did this.</p>
<p>The <code>landsat.nc</code> dataset is an image from Landsat Collection 2 Level-2, from the Microsof Planetary Computer data catalogue. Landsat Collection 2 Level-2 Science Products consist of atmospherically corrected surface reflectance and surface temperature image data. Collection 2 Level-2 Science Products are available from August 22, 1982 to present. It is accessed through my university but it can also be accessed on <a href="https://earthexplorer.usgs.gov/">USGS Earth Explorer</a>.</p>
<div id="cd12bd27-83cd-4861-af88-3f8900467896" class="cell" data-tags="[]" data-execution_count="3">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ---- Import data ----</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Import Thomas Fire boundary</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>thomas_fire <span class="op">=</span> gpd.read_file(<span class="st">"data/thomas_fire/thomas_fire.shp"</span>)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Import landsat .nc file</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>fp <span class="op">=</span> os.path.join(root,<span class="st">'landsat8-2018-01-26-sb-simplified.nc'</span>)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>landsat <span class="op">=</span> rioxr.open_rasterio(fp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, I will check the coordinate reference systems (CRS) of the <code>landsat</code> and <code>thomas_fire</code> datasets to ensure 1) the CRS aligns with the needs of the project and 2) the datasets share the same crs, allowing for proper overlay and analysis.</p>
<div id="dc20c9da-199d-4d49-8c5b-b765a3c7eb81" class="cell" data-tags="[]" data-execution_count="4">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ---- Check CRS information ----</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Check if landsat is projected </span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Is the landsat CRS projected?"</span>, landsat.rio.crs.is_projected)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Check if thomas fire is projected </span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Is the thomas_fire CRS projected?"</span>, thomas_fire.crs.is_projected)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Check if crs match</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Do the crs match?"</span>, landsat.rio.crs <span class="op">==</span> thomas_fire.crs)</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the crs name</span></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The landsat CRS is:"</span>, landsat.rio.crs)</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the crs name</span></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The thomas fire CRS is:"</span>, thomas_fire.crs.name)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Is the landsat CRS projected? True
Is the thomas_fire CRS projected? True
Do the crs match? False
The landsat CRS is: EPSG:32611
The thomas fire CRS is: WGS 84 / Pseudo-Mercator</code></pre>
</div>
</div>
<p>My analysis found that the <code>landsat</code> and <code>thomas_fire</code> crs were both projected, but did not match. This means that we need to reproject the data to match. So next, I’m going to reproject the <code>thomas_fire</code> CRS is to match that <code>landsat</code> CRS which is EPSG 32611 or WGS 84 / UTM Zone 11N.</p>
<div id="797c2f53-f61f-4efa-b27f-5323b1c9d63d" class="cell" data-tags="[]" data-execution_count="5">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ---- Reproject CRS ----</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Reproject to landsat crs</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>thomas_fire <span class="op">=</span> thomas_fire.to_crs(landsat.rio.crs)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Check if crs match</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Do the crs match?"</span>, landsat.rio.crs <span class="op">==</span> thomas_fire.crs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Do the crs match? True</code></pre>
</div>
</div>
</section>
<section id="step-1c.-explore-the-data" class="level4">
<h4 class="anchored" data-anchor-id="step-1c.-explore-the-data">Step 1C. Explore the Data</h4>
<p>Now that I have my data set up. I’m interested in learning more about the landsat data that I’ll be using. In the next code chunk, I explore different characteristics about my data.</p>
<div id="c9e787e1-4f54-4e40-9cbe-8c8b539ece70" class="cell" data-tags="[]" data-execution_count="6">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ---- Explore data ----</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Check out landsat data dimensions</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Size of landsat dimensions: '</span>, <span class="bu">dict</span>(landsat.sizes))</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Check out the shape of the landsat data</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The shape of Landsat is"</span>, landsat.rio.shape)</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Check out the variables of the landsat data</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Variables in the Landsat data:"</span>, <span class="bu">list</span>(landsat.data_vars))</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Check out the original coordiantes of the landsat data</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Variables in the Landsat data:"</span>, <span class="bu">list</span>(landsat.coords))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Size of landsat dimensions:  {'y': 731, 'x': 870, 'band': 1}
The shape of Landsat is (731, 870)
Variables in the Landsat data: ['red', 'green', 'blue', 'nir08', 'swir22']
Variables in the Landsat data: ['y', 'x', 'band', 'spatial_ref']</code></pre>
</div>
</div>
<p>It looks like the <code>landsat</code> data is 870 by 731 pixels. It has has a total of a band length of 1 and the list of variables in the dataset are ‘red’, ‘green’, ‘blue’, ‘nir08’, and ‘swir22’.</p>
</section>
<section id="step-1d.-prepare-the-landsat-data-for-visualization" class="level4">
<h4 class="anchored" data-anchor-id="step-1d.-prepare-the-landsat-data-for-visualization">Step 1D. Prepare the landsat data for visualization</h4>
<p>Since the landsat data only has one band, I’m going to simplify it by dropping the dimensions that so that it’s easier to work with. To do this, I’ll use <code>.squeeze()</code> and <code>.drop_vars()</code> to remove the band length of 1.</p>
<div id="07a6ca18-46c2-4a28-be5c-576e7a63c9e7" class="cell" data-tags="[]" data-execution_count="7">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove length 1 dimension (band) and reassign</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>landsat <span class="op">=</span> landsat.squeeze().drop_vars(<span class="st">'band'</span>, errors<span class="op">=</span><span class="st">'ignore'</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Check updated dimensions of the coordinates</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(landsat.dims, landsat.coords)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Size of landsat dimensions: '</span>, <span class="bu">dict</span>(landsat.sizes))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Frozen({'y': 731, 'x': 870}) Coordinates:
  * y            (y) float64 3.952e+06 3.952e+06 ... 3.756e+06 3.755e+06
  * x            (x) float64 1.213e+05 1.216e+05 ... 3.557e+05 3.559e+05
    spatial_ref  int64 0
Size of landsat dimensions:  {'y': 731, 'x': 870}</code></pre>
</div>
</div>
<p>I can see that the extra dimension has been removed from the data! Yipee!</p>
</section>
<section id="step-1e.-visualize-the-landsat-data-in-true-color" class="level3">
<h3 class="anchored" data-anchor-id="step-1e.-visualize-the-landsat-data-in-true-color">Step 1E. Visualize the Landsat data in true color</h3>
<p>Now I want to take a look at the landsat data. First off, it would be helpful to see the study area in “natural-color” also known as “true-color’, so that I can get a sense of what the terrain looks like. True-color is a term used by remote sensing experts to describe displaying a satellite image in colors similar to what most people would naturally see with their bare eyes. This means plotting the ‘red’, ‘green’, and ‘blue’ bands in their respective order.</p>
<p>Here I plot the landsat image in true color (R-G-B) to visualize what the burn area looks like over the region.</p>
<div id="4baf5a00-3239-4fc5-b68c-e95082c5f3c7" class="cell" data-tags="[]" data-execution_count="8">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the landsat bands in true color</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>landsat[[<span class="st">'red'</span>, <span class="st">'green'</span>, <span class="st">'blue'</span>]].to_array().plot.imshow()</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Thomas Fire Study Area"</span>) <span class="co"># Add title</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>plt.axis(<span class="st">'off'</span>) <span class="co"># Removing axis labels and ticks</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>plt.show() <span class="co"># Display the plot</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-9-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Hmmmmm…. something here doesn’t look right! The map shows up in black and white when I was expecting it to look like a true color image.</p>
<p>This is because the clouds in the image introduce extreme, outlier values. By setting the <code>robust = True</code> parameter in the in <code>.imshow()</code>, I adjust the color scale based on the 2nd and 98th percentiles of the values, which helps minimize the influence of these outliers. This allows the color ramp to more accurately reflect the distribution of values where most of the data lies, providing a clearer representation of the underlying true color patterns in the image.</p>
<div id="9ef11f81-78a6-4d5e-920a-c0da9390bc4d" class="cell" data-tags="[]" data-execution_count="9">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the landsat bands in true color</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>landsat[[<span class="st">'red'</span>, <span class="st">'green'</span>, <span class="st">'blue'</span>]].to_array().plot.imshow(robust<span class="op">=</span><span class="va">True</span>) <span class="co"># scale on the 2 &amp; 98th percentiles</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Thomas Fire Study Area"</span>) <span class="co"># Add title</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>plt.axis(<span class="st">'off'</span>) <span class="co"># Remove axis labels and ticks</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>plt.show() <span class="co"># Display the plot</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-10-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Ahhh, much better! Now this is more like what I was expecting to see in my true color image.</p>
<p>This map helps me get a feel for what the landscape looks like, but it is still difficult for me to distinguish between landcover like healthy vegetation and bare ground, since the green, brown, and tan colors don’t contrast strongly.</p>
</section>
<section id="step-1f.-visualize-the-landsat-data-in-false" class="level3">
<h3 class="anchored" data-anchor-id="step-1f.-visualize-the-landsat-data-in-false">Step 1F. Visualize the Landsat data in false</h3>
<p>Next, I’d like to see if I can visualize the burned area better by integrating other bands of the landsat image in a ‘false-color’ composite. False-color images use at least one wavelength outside the visible range, like near-infrared, which can highlight things that we can’t see with our bare eyes.</p>
<p>Vegetation strongly reflects in the near-infrared (NIR) and short-wave infrared (SWIR) bands and absorbs in the red, so visualizing these bands can help me distinguish between healthy vegetated from bare ground. For this reason, I will create a false-color composite using the SWIR, NIR, and red bands (SWIR-NIR-R) to better distinguish between vegetation and the Thomas Fire burned area.</p>
<div id="88640723-3080-410a-9f3d-c34828db97de" class="cell" data-tags="[]" data-execution_count="10">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Select and plot swir, nir, and red variables</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>landsat[[<span class="st">'swir22'</span>, <span class="st">'nir08'</span>, <span class="st">'red'</span>]].to_array().plot.imshow(robust<span class="op">=</span><span class="va">True</span>) <span class="co"># scale on the 2 &amp; 98th percentiles</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Thomas Fire Study Area"</span>) <span class="co"># Add title</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>plt.axis(<span class="st">'off'</span>) <span class="co"># Remove axis labels and ticks</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>plt.show() <span class="co"># Display the plot</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-11-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>That worked! Now I can much more easily distinguish between vegetation (green) and bare ground or stressed vegetation (tan and red). In the bottom right, I can make out a large irregular red shape which lines up with the area that the Thomas Fire burned.</p>
</section>
<section id="step-1g.-overlay-the-thomas-fire-boundary-on-the-false-color-image" class="level3">
<h3 class="anchored" data-anchor-id="step-1g.-overlay-the-thomas-fire-boundary-on-the-false-color-image">Step 1G. Overlay the Thomas Fire boundary on the false color image</h3>
<p>Now my final step is to overlay the false-color image with the Thomas Fire boundary to see how well the composite image picks up the burned area.</p>
<div id="eea35935-d163-4ab0-a2d5-3480799dc548" class="cell" data-tags="[]" data-execution_count="11">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ---- Create Map of Thomas Fire Boundary on False Color Image ----</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Select false color SWIR-NIR-red bands and set to array</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>false_color <span class="op">=</span> landsat[[<span class="st">'swir22'</span>, <span class="st">'nir08'</span>, <span class="st">'red'</span>]].to_array()</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Set aspect ratio for map</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>fire_aspect_ratio <span class="op">=</span> landsat.rio.shape[<span class="dv">1</span>] <span class="op">/</span> landsat.rio.shape[<span class="dv">0</span>]</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Set figure parameters</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">6</span>, <span class="dv">6</span><span class="op">*</span>fire_aspect_ratio))</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Add false color imagery for background</span></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>false_color.plot.imshow(ax <span class="op">=</span> ax,</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>                        robust<span class="op">=</span><span class="va">True</span>) </span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Add thomas fire boundary</span></span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>thomas_fire.boundary.plot(ax<span class="op">=</span>ax,</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>                color <span class="op">=</span> <span class="st">"#780B12"</span>,</span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>                linewidth <span class="op">=</span> <span class="fl">0.6</span>,</span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>                alpha <span class="op">=</span> <span class="fl">0.8</span>)</span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Add title</span></span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">'Thomas Fire Boundary (2017)         Southern California'</span>,</span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a>            color<span class="op">=</span><span class="st">"#222626"</span>, </span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a>            fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a>ax.axis(<span class="st">'off'</span>) <span class="co"># Remove axis labels and ticks</span></span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a>plt.legend(thomas_fire,loc<span class="op">=</span><span class="st">'upper right'</span>, labels <span class="op">=</span> [<span class="st">"Thomas Fire"</span>]) <span class="co"># add legend</span></span>
<span id="cb15-27"><a href="#cb15-27" aria-hidden="true" tabindex="-1"></a>plt.show() <span class="co"># Display the plot</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-12-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>This map shows the burn perimeter, outlined in dark red, for the Thomas Fire which occured in 2017. The boundary is overlayed onto a false color satellite image of the region, combining short-wave infrared (SWIR), near-infrared (NIR), and red bands to highlight vegetation (green) versus the burn scar (red). This overlay shows that the boundary of the burn scar aligns well with area in red in false color composite. When looking back at the true color image, this false-color map demonstrates the ability of the false color images to pick out land surface characteristics beyond what our bare eyes can see.</p>
<div id="b501535e-bf41-418d-932f-43203e7f5d03" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Display all columns in preview</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>pd.set_option(<span class="st">"display.max.columns"</span>, <span class="va">None</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="part-2.-timeseries-analysis-of-the-thomas-fires-impact-on-regional-air-quality" class="level2">
<h2 class="anchored" data-anchor-id="part-2.-timeseries-analysis-of-the-thomas-fires-impact-on-regional-air-quality">Part 2. Timeseries Analysis of the Thomas Fire’s Impact on Regional Air Quality</h2>
<p><img src="nasa-eo-smoke.jpg" class="img-fluid"></p>
<p>Source: <a href="https://earthobservatory.nasa.gov/images/91421/fires-continue-to-rage-in-southern-california">NASA Earth Observatory</a></p>
<p>In the next section, I explore the impact of the Thomas Fire on air quality using <a href="https://www.airnow.gov/aqi/aqi-basics/">Air Quality Index</a> (AQI) data. The U.S Environmental Protection Agency’s (EPA) AQI is a standard scale that measures air quality and its associated health impacts.</p>
<p><img src="AQI.jpg" class="img-fluid"></p>
<p>Source: <a href="https://www.epa.gov/">U.S. EPA</a></p>
<p>This table shows the six AQI levels, where a higher AQI corresponds with more severe health concerns.</p>
<p>For this exercise I use regional AQI data from the <a href="https://www.epa.gov/">U.S. EPA</a>. Some of the technical highlights for this section include data wrangling with <code>pandas</code> , numerical processing with <code>numpy</code>, and time series data visualization with <code>matplotlib</code>.</p>
<section id="step-2a-set-up-my-workspace" class="level3">
<h3 class="anchored" data-anchor-id="step-2a-set-up-my-workspace">Step 2A: Set up my workspace</h3>
<p>To begin, I set up my workspace by loading in the libraries that are necessary for the analysis:</p>
<div id="3206588b-9a1a-4633-b24e-eb1d088849ec" class="cell" data-tags="[]" data-execution_count="13">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import libraries</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="step-2b-import-prepare-data" class="level3">
<h3 class="anchored" data-anchor-id="step-2b-import-prepare-data">Step 2B: Import &amp; prepare data</h3>
<p>Now it’s time to read in my project data!</p>
<p>The <code>aqi_17.csv</code> and <code>aqi_18.csv</code> are files containing AQI observations from air quality monitors for the 2017 and 2018 years, respectively, in the Thomas Fire region. I read in the data directly from the <a href="https://www.airnow.gov/aqi/aqi-basics/">Air Quality Index (AQI) Basics</a> on the AirNow.gov portal.</p>
<div id="abe363c6-4b8e-42ad-946f-abea20e8a0d8" class="cell" data-tags="[]" data-execution_count="14">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Read in AQI data</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>aqi_17 <span class="op">=</span> pd.read_csv(<span class="st">'data/aqi/daily_aqi_by_county_2017.zip'</span>, compression<span class="op">=</span><span class="st">'zip'</span>)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>aqi_18 <span class="op">=</span> pd.read_csv(<span class="st">'data/aqi/daily_aqi_by_county_2018.zip'</span>, compression<span class="op">=</span><span class="st">'zip'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="step-2c.-explore-the-data" class="level3">
<h3 class="anchored" data-anchor-id="step-2c.-explore-the-data">Step 2C. Explore the Data</h3>
<p>Now that I have my data set up, I’m interested in learning more about the AQI data that I’ll be using. In the next code chunk, I explore different characteristics about my data.</p>
<div id="ac95b84b-33a5-454d-9857-7ee8cc046f7d" class="cell" data-tags="[]" data-execution_count="15">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Look at the head, first 5 entries, of the AQI 2017 data</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>aqi_17.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="15">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">State Name</th>
<th data-quarto-table-cell-role="th">county Name</th>
<th data-quarto-table-cell-role="th">State Code</th>
<th data-quarto-table-cell-role="th">County Code</th>
<th data-quarto-table-cell-role="th">Date</th>
<th data-quarto-table-cell-role="th">AQI</th>
<th data-quarto-table-cell-role="th">Category</th>
<th data-quarto-table-cell-role="th">Defining Parameter</th>
<th data-quarto-table-cell-role="th">Defining Site</th>
<th data-quarto-table-cell-role="th">Number of Sites Reporting</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Alabama</td>
<td>Baldwin</td>
<td>1</td>
<td>3</td>
<td>2017-01-01</td>
<td>28</td>
<td>Good</td>
<td>PM2.5</td>
<td>01-003-0010</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Alabama</td>
<td>Baldwin</td>
<td>1</td>
<td>3</td>
<td>2017-01-04</td>
<td>29</td>
<td>Good</td>
<td>PM2.5</td>
<td>01-003-0010</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Alabama</td>
<td>Baldwin</td>
<td>1</td>
<td>3</td>
<td>2017-01-10</td>
<td>25</td>
<td>Good</td>
<td>PM2.5</td>
<td>01-003-0010</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>Alabama</td>
<td>Baldwin</td>
<td>1</td>
<td>3</td>
<td>2017-01-13</td>
<td>40</td>
<td>Good</td>
<td>PM2.5</td>
<td>01-003-0010</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>Alabama</td>
<td>Baldwin</td>
<td>1</td>
<td>3</td>
<td>2017-01-16</td>
<td>22</td>
<td>Good</td>
<td>PM2.5</td>
<td>01-003-0010</td>
<td>1</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="21fad2c9-07fb-4270-89da-2b0ba3d84d8e" class="cell" data-scrolled="true" data-tags="[]" data-execution_count="16">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Look at the head, first 5 entries, of the AQI 2018 data</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>aqi_18.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="16">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">State Name</th>
<th data-quarto-table-cell-role="th">county Name</th>
<th data-quarto-table-cell-role="th">State Code</th>
<th data-quarto-table-cell-role="th">County Code</th>
<th data-quarto-table-cell-role="th">Date</th>
<th data-quarto-table-cell-role="th">AQI</th>
<th data-quarto-table-cell-role="th">Category</th>
<th data-quarto-table-cell-role="th">Defining Parameter</th>
<th data-quarto-table-cell-role="th">Defining Site</th>
<th data-quarto-table-cell-role="th">Number of Sites Reporting</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Alabama</td>
<td>Baldwin</td>
<td>1</td>
<td>3</td>
<td>2018-01-02</td>
<td>42</td>
<td>Good</td>
<td>PM2.5</td>
<td>01-003-0010</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Alabama</td>
<td>Baldwin</td>
<td>1</td>
<td>3</td>
<td>2018-01-05</td>
<td>45</td>
<td>Good</td>
<td>PM2.5</td>
<td>01-003-0010</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Alabama</td>
<td>Baldwin</td>
<td>1</td>
<td>3</td>
<td>2018-01-08</td>
<td>20</td>
<td>Good</td>
<td>PM2.5</td>
<td>01-003-0010</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>Alabama</td>
<td>Baldwin</td>
<td>1</td>
<td>3</td>
<td>2018-01-11</td>
<td>25</td>
<td>Good</td>
<td>PM2.5</td>
<td>01-003-0010</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>Alabama</td>
<td>Baldwin</td>
<td>1</td>
<td>3</td>
<td>2018-01-14</td>
<td>33</td>
<td>Good</td>
<td>PM2.5</td>
<td>01-003-0010</td>
<td>1</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="094a26fb-a665-4249-8d5e-19380686665c" class="cell" data-tags="[]" data-execution_count="17">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Explore the spread of AQI observation values</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Max AQI for 2017 ="</span>, aqi_17[<span class="st">'AQI'</span>].<span class="bu">max</span>())</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Min AQI for 2017 ="</span>, aqi_17[<span class="st">'AQI'</span>].<span class="bu">min</span>())</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Max AQI for 2018 ="</span>, aqi_18[<span class="st">'AQI'</span>].<span class="bu">max</span>())</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Min AQI for 2018 ="</span>, aqi_18[<span class="st">'AQI'</span>].<span class="bu">min</span>())</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Explore data types</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(aqi_17.dtypes)</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(aqi_18.dtypes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Max AQI for 2017 = 3767
Min AQI for 2017 = 0
Max AQI for 2018 = 1051
Min AQI for 2018 = 0
State Name                   object
county Name                  object
State Code                    int64
County Code                   int64
Date                         object
AQI                           int64
Category                     object
Defining Parameter           object
Defining Site                object
Number of Sites Reporting     int64
dtype: object
State Name                   object
county Name                  object
State Code                    int64
County Code                   int64
Date                         object
AQI                           int64
Category                     object
Defining Parameter           object
Defining Site                object
Number of Sites Reporting     int64
dtype: object</code></pre>
</div>
</div>
<p>In the data exploration above, I used <code>dtypes</code> to see the data types for the different columns. I also used <code>max</code> and <code>min</code> to find the maximum and minimum AQI values for the datasets. Then I used <code>value_counts</code> to find the value counts of observations that fell in the different category ratings.</p>
</section>
<section id="step-2d.-prepare-the-aqi-data-for-visualization" class="level3">
<h3 class="anchored" data-anchor-id="step-2d.-prepare-the-aqi-data-for-visualization">Step 2D. Prepare the AQI data for visualization</h3>
<p>Great, now I’m familiar with the AQI data that I’ll be using, it’s time to prepare it for visualization. Since <code>aqi_17</code> and <code>aqi_18</code> are saved as two separated data frames, I want to merge them together using the <code>pd.concat()</code> tool and store the output as <code>aqi</code>.</p>
<div id="210c727d-bb42-4f29-ac25-a451bf1038a1" class="cell" data-tags="[]" data-execution_count="18">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ---- Combine the datasets ----</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine the two datasets using `pd.concat`</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>aqi <span class="op">=</span> pd.concat([aqi_17, aqi_18])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now that we have combined the datasets, I want to take a look at what the new dataframe looks like.</p>
<div id="614e95bc-12c8-4163-bbe3-c8d27b1bd8dc" class="cell" data-tags="[]" data-execution_count="19">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ---- Explore the AQI data ----</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Check out the head of the new df</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(aqi.head())</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Check out column names</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The column names area:"</span>, <span class="bu">list</span>(aqi.columns))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  State Name county Name  State Code  County Code        Date  AQI Category  \
0    Alabama     Baldwin           1            3  2017-01-01   28     Good   
1    Alabama     Baldwin           1            3  2017-01-04   29     Good   
2    Alabama     Baldwin           1            3  2017-01-10   25     Good   
3    Alabama     Baldwin           1            3  2017-01-13   40     Good   
4    Alabama     Baldwin           1            3  2017-01-16   22     Good   

  Defining Parameter Defining Site  Number of Sites Reporting  
0              PM2.5   01-003-0010                          1  
1              PM2.5   01-003-0010                          1  
2              PM2.5   01-003-0010                          1  
3              PM2.5   01-003-0010                          1  
4              PM2.5   01-003-0010                          1  
The column names area: ['State Name', 'county Name', 'State Code', 'County Code', 'Date', 'AQI', 'Category', 'Defining Parameter', 'Defining Site', 'Number of Sites Reporting']</code></pre>
</div>
</div>
<p>Oooof! I do not like the look of the column names. Their naming convention is all over the place, with all those capitalizations and spaces. This can be annoying to work with in Python, so I’ll want to tidy it up so that it’s easier to work with!</p>
<p>I want to change my column names to <code>lower snake case</code>, a popular naming convention that uses lowercase letters and underscores to separate words.</p>
<p>In this next code chunk, I’m going to convert the column names to <code>lower snake case</code>, a popular naming convention that uses lowercase letters and underscores to separate words. I’ll do this by selecting the columns using <code>.columns</code>, forcing all strings (text) to lower case using <code>.lower()</code>, and replacing all spaces <code>' '</code>with underscores <code>'_'</code> using <code>.replace()</code>.</p>
<div id="03c41d43-576d-47cc-b42b-e1d050d7c9de" class="cell" data-tags="[]" data-execution_count="20">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Simplify column names</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>aqi.columns <span class="op">=</span> (aqi.columns <span class="co"># Selects column names of the aqi df</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>                  .<span class="bu">str</span>.lower() <span class="co"># Forces text to lower case</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>                  .<span class="bu">str</span>.replace(<span class="st">' '</span>,<span class="st">'_'</span>) <span class="co"># replaces spaces ' ' with underscores '_'</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>                )</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The column names are:"</span>, <span class="bu">list</span>(aqi.columns)) <span class="co"># print the updated column names</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The column names are: ['state_name', 'county_name', 'state_code', 'county_code', 'date', 'aqi', 'category', 'defining_parameter', 'defining_site', 'number_of_sites_reporting']</code></pre>
</div>
</div>
</section>
<section id="step-2e.-subset-prepare-aqi-data-for-timeseries-visualization" class="level3">
<h3 class="anchored" data-anchor-id="step-2e.-subset-prepare-aqi-data-for-timeseries-visualization">Step 2E. Subset &amp; prepare <code>aqi</code> data for timeseries visualization</h3>
<p>Now that I’ve cleaned up my data, it’s time to start some wrangling! I’m going to subset <code>aqi</code> to Santa Barbara county by selecting the column where <code>'county_name'</code> is <code>Santa Barbara</code>. I also want to remove some of the column names that I won’t be using for my visualization including <code>'state_name'</code>, <code>'county_name'</code>, <code>'state_code'</code>, and <code>'county_code'</code>.</p>
<div id="037150e4-e86e-446e-a271-38c9b35c58ff" class="cell" data-tags="[]" data-execution_count="21">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ---- Subset `aqi` data for visualization ----</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Subset AQI data to Santa Barbara county</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>aqi <span class="op">=</span> aqi[aqi[<span class="st">'county_name'</span>] <span class="op">==</span> <span class="st">'Santa Barbara'</span>]</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove the 'state_name', 'county_name', 'state_code' and 'county_code' columns from aqi_sb</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>aqi <span class="op">=</span> aqi.drop([<span class="st">'state_name'</span>, <span class="st">'county_name'</span>, <span class="st">'state_code'</span>, <span class="st">'county_code'</span>], axis <span class="op">=</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Awesome, now my data is subset to my area of interest!</p>
<p>Next I have want to prepare the date column so that I can visualize <code>aqi</code> as a time series.</p>
<p>Let me check out how the date column is being stored using <code>type()</code>.</p>
<div id="c6633613-ad93-48a7-a1f2-e435ad52a8fe" class="cell" data-tags="[]" data-execution_count="22">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check the type of date column</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>date_type <span class="op">=</span> <span class="bu">type</span>(aqi.date)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>date_type</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="22">
<pre><code>pandas.core.series.Series</code></pre>
</div>
</div>
<p>It looks like it is a <code>pandas.core.series.Series</code>, so I will want to update the date column to be a <code>pandas.datetime</code> object using <code>pd.to_datetime()</code>.</p>
<div id="f5233a1b-02f8-451c-ae52-1543fae25ae9" class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Update the data column to datetime object</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>aqi.date <span class="op">=</span> pd.to_datetime(aqi.date)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>And now lets set the <code>'date'</code> column as the index for the <code>aqi</code> dataframe using <code>.set_index</code>.</p>
<div id="75506728-5d0d-4658-9051-9381e066c86c" class="cell" data-tags="[]" data-execution_count="24">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set date as the index of aqi_sb</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>aqi <span class="op">=</span> aqi.set_index(<span class="st">'date'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="step-2f.-calculate-5-day-rolling-average-for-aqi" class="level3">
<h3 class="anchored" data-anchor-id="step-2f.-calculate-5-day-rolling-average-for-aqi">Step 2F. Calculate 5-Day Rolling Average for AQI</h3>
<p>Before I create the timeseries plot, I’d like to smooth out the data a bit by calculating the average over a rolling, 5-day window. In python we can do this using <code>.rolling()</code> by specifying the window length as <code>'5D'</code> and the type of calculation to be <code>.mean()</code>.</p>
<div id="50141971-d2e0-4399-81b3-e4e150de7425" class="cell" data-tags="[]" data-execution_count="25">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate AQI rolling average over 5 days</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>rolling_average <span class="op">=</span> (aqi[<span class="st">'aqi'</span>]</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>                   .rolling(window <span class="op">=</span> <span class="st">'5D'</span>) <span class="co"># Specify window length</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>                   .mean()) <span class="co"># Specify caluation as mean</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>rolling_average</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="25">
<pre><code>date
2017-01-01    39.000000
2017-01-02    39.000000
2017-01-03    49.666667
2017-01-04    45.750000
2017-01-05    44.000000
                ...    
2018-12-27    41.200000
2018-12-28    38.600000
2018-12-29    38.200000
2018-12-30    38.200000
2018-12-31    38.800000
Name: aqi, Length: 730, dtype: float64</code></pre>
</div>
</div>
<p>Now, let’s add these calculations to the <code>aqi</code> dataframe.</p>
<div id="1ea4ca81-a0f4-4736-b433-1251943fcc4e" class="cell" data-tags="[]" data-execution_count="26">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add calculated rolling averages as 'five_day_average' column</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>aqi[<span class="st">"five_day_average"</span>] <span class="op">=</span> rolling_average</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>aqi</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="26">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">aqi</th>
<th data-quarto-table-cell-role="th">category</th>
<th data-quarto-table-cell-role="th">defining_parameter</th>
<th data-quarto-table-cell-role="th">defining_site</th>
<th data-quarto-table-cell-role="th">number_of_sites_reporting</th>
<th data-quarto-table-cell-role="th">five_day_average</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">date</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">2017-01-01</td>
<td>39</td>
<td>Good</td>
<td>Ozone</td>
<td>06-083-4003</td>
<td>12</td>
<td>39.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2017-01-02</td>
<td>39</td>
<td>Good</td>
<td>PM2.5</td>
<td>06-083-2011</td>
<td>11</td>
<td>39.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2017-01-03</td>
<td>71</td>
<td>Moderate</td>
<td>PM10</td>
<td>06-083-4003</td>
<td>12</td>
<td>49.666667</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2017-01-04</td>
<td>34</td>
<td>Good</td>
<td>Ozone</td>
<td>06-083-4003</td>
<td>13</td>
<td>45.750000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2017-01-05</td>
<td>37</td>
<td>Good</td>
<td>Ozone</td>
<td>06-083-4003</td>
<td>12</td>
<td>44.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2018-12-27</td>
<td>37</td>
<td>Good</td>
<td>Ozone</td>
<td>06-083-1025</td>
<td>11</td>
<td>41.200000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2018-12-28</td>
<td>39</td>
<td>Good</td>
<td>Ozone</td>
<td>06-083-1021</td>
<td>12</td>
<td>38.600000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2018-12-29</td>
<td>39</td>
<td>Good</td>
<td>Ozone</td>
<td>06-083-1021</td>
<td>12</td>
<td>38.200000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2018-12-30</td>
<td>41</td>
<td>Good</td>
<td>PM2.5</td>
<td>06-083-1008</td>
<td>12</td>
<td>38.200000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2018-12-31</td>
<td>38</td>
<td>Good</td>
<td>Ozone</td>
<td>06-083-2004</td>
<td>12</td>
<td>38.800000</td>
</tr>
</tbody>
</table>

<p>730 rows × 6 columns</p>
</div>
</div>
</div>
</section>
<section id="step-2e.-create-aqi-time-series-plot-for-the-thomas-fire" class="level3">
<h3 class="anchored" data-anchor-id="step-2e.-create-aqi-time-series-plot-for-the-thomas-fire">Step 2E. Create AQI Time Series Plot for the Thomas Fire</h3>
<p>Phew! Now that I have the data all set up, it’s <em>finally</em> time to create a visualization. I’m going to plot <code>aqi</code> as a timeseries to explore how it was impacted by the Thomas Fire.</p>
<p>In this next code chunk, I’ll create the plot along with some custom formatting elements to help provide context for the figure using <code>matplotlib()</code>. I’ll set up <code>'date'</code> on the x-axis and <code>aqi</code> and <code>rolling_average</code> on the y axis.</p>
<p>I’ll add a vertical span <code>plt.axvspan</code> and annotation <code>plt.annotate</code> in transparent red to shade in the duration of the Thomas Fire. To indicate benchmarks for ‘unhealthy’, ‘very unhealthy’, and ‘hazardous’ aqi levels I’ll using <code>plt.axhline</code> and <code>plt.text</code> to add horizontal dashed lines.</p>
<p>To finish it off, I’ll incorporate custom layout settings including a title, axis labels, gridlines, and a legend.</p>
<div id="2978dec0-4ddd-41ea-a7a3-97917b317927" class="cell" data-tags="[]" data-execution_count="27">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set figure size (wider plot)</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">6</span>)) </span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="co"># ---- Add vertical and horizontal labels ----</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Add vertical span indicating Thomas Fire duration</span></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>plt.axvspan(pd.to_datetime(<span class="st">'2017-12-04'</span>), pd.to_datetime(<span class="st">'2018-01-12'</span>), color <span class="op">=</span><span class="st">'#A3210D'</span>, alpha <span class="op">=</span> <span class="fl">0.05</span>)</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>plt.annotate(<span class="st">'Thomas Fire'</span>, xy <span class="op">=</span> (pd.to_datetime(<span class="st">'2018-01-12'</span>), <span class="dv">200</span>), xytext <span class="op">=</span> (pd.to_datetime(<span class="st">'2018-01-12'</span>), <span class="dv">230</span>),</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>             arrowprops<span class="op">=</span><span class="bu">dict</span>(arrowstyle <span class="op">=</span> <span class="st">'-'</span>, color<span class="op">=</span><span class="st">'#A3210D'</span>), color<span class="op">=</span><span class="st">'#A3210D'</span>, alpha<span class="op">=</span><span class="fl">0.7</span>)</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Add dashed horizontal lines for AQI levels</span></span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a>plt.axhline(y<span class="op">=</span><span class="dv">151</span>, color <span class="op">=</span> <span class="st">'orange'</span>, linestyle <span class="op">=</span><span class="st">'--'</span>, label <span class="op">=</span><span class="st">'_nolegend_'</span>, linewidth<span class="op">=</span><span class="fl">1.5</span>)</span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a>plt.axhline(y<span class="op">=</span><span class="dv">201</span>, color <span class="op">=</span> <span class="st">'red'</span>, linestyle <span class="op">=</span><span class="st">'--'</span>, label <span class="op">=</span><span class="st">'_nolegend_'</span>, linewidth<span class="op">=</span><span class="fl">1.5</span>)</span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a>plt.axhline(y<span class="op">=</span><span class="dv">301</span>, color <span class="op">=</span> <span class="st">'purple'</span>, linestyle <span class="op">=</span><span class="st">'--'</span>, label <span class="op">=</span><span class="st">'_nolegend_'</span>, linewidth<span class="op">=</span><span class="fl">1.5</span>)</span>
<span id="cb36-15"><a href="#cb36-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-16"><a href="#cb36-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Add text labels on the lines, moved right by a bit for better placement</span></span>
<span id="cb36-17"><a href="#cb36-17" aria-hidden="true" tabindex="-1"></a>plt.text(aqi.index[<span class="dv">0</span>] <span class="op">+</span> pd.Timedelta(days <span class="op">=</span> <span class="dv">20</span>), <span class="dv">151</span>, <span class="st">'Unhealthy'</span>, color <span class="op">=</span><span class="st">'orange'</span>, fontsize<span class="op">=</span><span class="dv">10</span>, verticalalignment<span class="op">=</span><span class="st">'bottom'</span>)</span>
<span id="cb36-18"><a href="#cb36-18" aria-hidden="true" tabindex="-1"></a>plt.text(aqi.index[<span class="dv">0</span>] <span class="op">+</span> pd.Timedelta(days <span class="op">=</span> <span class="dv">20</span>), <span class="dv">201</span>, <span class="st">'Very Unhealthy'</span>, color <span class="op">=</span><span class="st">'red'</span>, fontsize<span class="op">=</span><span class="dv">10</span>, verticalalignment<span class="op">=</span><span class="st">'bottom'</span>)</span>
<span id="cb36-19"><a href="#cb36-19" aria-hidden="true" tabindex="-1"></a>plt.text(aqi.index[<span class="dv">0</span>] <span class="op">+</span> pd.Timedelta(days <span class="op">=</span> <span class="dv">20</span>), <span class="dv">301</span>, <span class="st">'Hazardous'</span>, color <span class="op">=</span><span class="st">'purple'</span>, fontsize<span class="op">=</span><span class="dv">10</span>, verticalalignment<span class="op">=</span><span class="st">'bottom'</span>)</span>
<span id="cb36-20"><a href="#cb36-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-21"><a href="#cb36-21" aria-hidden="true" tabindex="-1"></a><span class="co"># ---- Plot AQI data ----</span></span>
<span id="cb36-22"><a href="#cb36-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-23"><a href="#cb36-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot AQI and 5-day average</span></span>
<span id="cb36-24"><a href="#cb36-24" aria-hidden="true" tabindex="-1"></a>plt.plot(aqi.index, aqi.aqi, color<span class="op">=</span><span class="st">'#80C4B4'</span>, label<span class="op">=</span><span class="st">'Daily AQI'</span>)</span>
<span id="cb36-25"><a href="#cb36-25" aria-hidden="true" tabindex="-1"></a>plt.plot(aqi.index, aqi.five_day_average, color<span class="op">=</span><span class="st">'#596964'</span>, label<span class="op">=</span><span class="st">'5-Day Average AQI'</span>)</span>
<span id="cb36-26"><a href="#cb36-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-27"><a href="#cb36-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-28"><a href="#cb36-28" aria-hidden="true" tabindex="-1"></a><span class="co"># ---- Customize layout ----</span></span>
<span id="cb36-29"><a href="#cb36-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-30"><a href="#cb36-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Title and Labels</span></span>
<span id="cb36-31"><a href="#cb36-31" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Air Quality Index (AQI) Spike During the 2017 Thomas Fire in Santa Barbara County'</span>, fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb36-32"><a href="#cb36-32" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Date'</span>, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb36-33"><a href="#cb36-33" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'AQI'</span>, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb36-34"><a href="#cb36-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-35"><a href="#cb36-35" aria-hidden="true" tabindex="-1"></a><span class="co"># Customize ticks</span></span>
<span id="cb36-36"><a href="#cb36-36" aria-hidden="true" tabindex="-1"></a>plt.xticks(rotation <span class="op">=</span><span class="dv">45</span>, ha <span class="op">=</span><span class="st">'right'</span>)</span>
<span id="cb36-37"><a href="#cb36-37" aria-hidden="true" tabindex="-1"></a>plt.yticks(<span class="bu">range</span>(<span class="dv">0</span>, <span class="dv">350</span>, <span class="dv">50</span>))</span>
<span id="cb36-38"><a href="#cb36-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-39"><a href="#cb36-39" aria-hidden="true" tabindex="-1"></a><span class="co"># Add gridlines for better readability</span></span>
<span id="cb36-40"><a href="#cb36-40" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>, linestyle <span class="op">=</span><span class="st">'--'</span>, alpha <span class="op">=</span> <span class="fl">0.2</span>)</span>
<span id="cb36-41"><a href="#cb36-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-42"><a href="#cb36-42" aria-hidden="true" tabindex="-1"></a><span class="co"># Add Legend</span></span>
<span id="cb36-43"><a href="#cb36-43" aria-hidden="true" tabindex="-1"></a>plt.legend(bbox_to_anchor <span class="op">=</span> (<span class="fl">1.05</span>, <span class="dv">1</span>), loc <span class="op">=</span> <span class="st">'upper left'</span>, fontsize<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb36-44"><a href="#cb36-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-45"><a href="#cb36-45" aria-hidden="true" tabindex="-1"></a><span class="co"># Show plot</span></span>
<span id="cb36-46"><a href="#cb36-46" aria-hidden="true" tabindex="-1"></a>plt.tight_layout() <span class="co"># Minimizes padding</span></span>
<span id="cb36-47"><a href="#cb36-47" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-28-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>This is a timeseries plot of <code>aqi</code> during the Thomas Fire in Santa Barbara County with date on the x-axis and aqi (light blue) and 5-day rolling average (dark green) on the y-axis. The figure shows a distinct spike in AQI in late 2017, during the Thomas Fire which burned from December 4, 2017 through January 12, 2018. At the start of the fire, the Daily AQI spiked above “Hazardous” AQI level, 300, which warns of emergency conditions where everyone, not just senstive populations, are likely to face health effects. The figure identifies an additional brief but significant spike in Santa Barbara, where the AQI rose above 200, which the EPA ranks as ‘Very Unhealthy’; this could suggest the occurance of another fire or event that contributed to the dramatic spike.</p>
<p>This timeseries is an effective way to tell the story of how fires can affect AQI and pose a significant risk to human health.</p>
<p><em>That’s it for my step-by-step analysis of the Thomas Fire. I hope that you enjoyed following along!</em></p>
</section>
<section id="references" class="level3">
<h3 class="anchored" data-anchor-id="references">References:</h3>
<p>CAL FIRE (2024) <em>California Fire Perimeters (all)</em> [Data file] Available from: https://catalog.data.gov/dataset/california-fire-perimeters-all-b3436 Access date: 11/20/24</p>
<p>USGS (2024) <em>Landsat Collection 2 Level-2 Surface Reflectance and Surface Temperature Products</em> [Data file]. Available from: https://www.usgs.gov/landsat-missions/landsat-collection-2 Access date: 11/20/24</p>
<p>EPA (2024) <em>Daily AQI By County 2017 &amp; 2018</em> [Data file] Available from: https://www.epa.gov/ Access date: 12/04/24</p>
<p>Carmen Galaz García (2024) <em>UCSB MEDS - 220 - Working With Environmental Datasets </em> [Source of Homework Assignment]. Course Website: https://meds-eds-220.github.io/MEDS-eds-220-course/ Access date: 11/20/24</p>


</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" id="quarto-citation"><h2 class="anchored quarto-appendix-heading">Citation</h2><div><div class="quarto-appendix-secondary-label">BibTeX citation:</div><pre class="sourceCode code-with-copy quarto-appendix-bibtex"><code class="sourceCode bibtex">@online{pepper2024,
  author = {Pepper, Nicole},
  title = {A {Step-By-Step} {Analysis} of the {Impacts} of the {Thomas}
    {Fire}},
  date = {2024-12-04},
  url = {https://nicolelpepper.github.io/personalwebsite/blogs/2024-12-02-thomas-fire/},
  langid = {en}
}
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre><div class="quarto-appendix-secondary-label">For attribution, please cite this work as:</div><div id="ref-pepper2024" class="csl-entry quarto-appendix-citeas" role="listitem">
Pepper, Nicole. 2024. <span>“A Step-By-Step Analysis of the Impacts of
the Thomas Fire.”</span> December 4, 2024. <a href="https://nicolelpepper.github.io/personalwebsite/blogs/2024-12-02-thomas-fire/">https://nicolelpepper.github.io/personalwebsite/blogs/2024-12-02-thomas-fire/</a>.
</div></div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Copyright 2025, Nicole Pepper</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>This website was built with <i class="fa-brands fa-github" title="GitHub" aria-label="github"></i></p>
</div>
  </div>
</footer>




</body></html>